name: "Setup and Greet"
description: "Print greeting and runner information"

inputs:
  name:
    description: "Name of the user"
    required: true

  language:
    description: "Greeting language"
    required: false
    default: "en"

outputs:
  greeted:
    description: "Whether greeting executed"
    value: ${{ steps.greet.outputs.greeted }}

runs:
  using: "composite"

  steps:
    - name: Print Greeting
      id: greet
      shell: bash
      run: |
          case "${{ inputs.language }}" in
          fr) echo "Bonjour, ${{ inputs.name }}!" ;;
          es) echo "Hola, ${{ inputs.name }}!" ;;
          *) echo "Hello, ${{ inputs.name }}!" ;;
          esac

      echo "Current Date: $(date)"
      echo "Runner OS: $RUNNER_OS"

      echo "greeted=true" >> $GITHUB_OUTPUT