name: Github Hosted Runners Demo

on:
    push:

jobs:
    ubuntu-job:
        runs-on: ubuntu-latest
        steps:
            - name: print runner info
              run: |
                    echo "OS: $(uname -a)"
                    echo "Hostname: $(hostname)"
                    echo "User: $(whoami)"

    windows-job:
        runs-on: windows-latest
        steps:
           - name: Print runner info
             run: |
                   echo OS: $env:OS
                   hostname
                   whoami

    macos-job:
        runs-on: macos-latest
        steps:
             - name: Print runner info
               run: |
                    echo "OS: $(uname -a)"
                    echo "Hostname: $(hostname)"
                    echo "User: $(whoami)"