---
name: scheduled workflow
on:
  schedule:
        - cron: "0 9 * * 1"

jobs:
    run_schedule:
      runs-on: ubuntu-latest
      steps:
        - name: Print message
          run: echo "Scheduled workflow running at midnight UTC"